# Generated by Django 4.2.14 on 2024-08-06 11:25

from django.db import migrations, models
import part.models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0122_parttesttemplate_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(default=part.models.get_next_part_number, help_text='Part number', max_length=100, verbose_name='Number'),
        ),
    ]
