# Generated by Django 4.2.14 on 2024-08-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_company_active'),
        ('part', '0123_alter_part_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPN', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_parts_ok', to='company.company')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_parts_ok', to='part.part')),
            ],
        ),
    ]
