# Generated by Django 4.2.14 on 2024-08-08 07:00

from django.db import migrations, models
import part.models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0124_manufacturerpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='IPN',
            field=models.CharField(blank=True, default=part.models.Part.generate_ipn, help_text='Internal Part Number', max_length=100, null=True, verbose_name='IPN'),
        ),
    ]
