# Generated by Django 4.2.14 on 2024-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0125_alter_part_ipn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, help_text='Part description (optional)', max_length=111, verbose_name='Description'),
        ),
    ]
