# Generated by Django 4.2.14 on 2024-08-14 12:30

from django.db import migrations, models
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0013_alter_partlabel_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlabel',
            name='filters',
            field=models.CharField(blank=True, help_text='Query filters (comma-separated list of key=value pairs)', max_length=250, validators=[label.models.validate_part_filters], verbose_name='Filters'),
        ),
    ]
